### ISSUE TITLE
Lava Source Blocks

### ISSUE THREAD

**Issue by Versimno** [kreezxil/Lava-Dynamics#3]
I feel flowing lava generating more lava is a bit too cheaty, as players can harvest if for other uses. Is it possible to add a config for this feature so I can disable it, or instead of placing a new source block, a 'flowing lava' is placed? Or maybe even a unharvestable fake lava block. That way players can't just take one lava and a bunch of wood and get unlimited buckets of lava.

**Comment by kreezxil** [comment]
The Nether is really cheat in this regard. You can ban obsidian so players
won't have access to all those free lava source blocks. My goal is to not
add new blocks to Minecraft but simply to change the behavior. I will
however add a config to disable source block in which case another flowing
block is added. Thanks for the input.

**Comment by kreezxil** [comment]
1.12.2-2.2.9 now has a config to disable that feature during lava spread. It is impossible to place flowing lava without it turning immediately into a lava source block, so instead of seeing lava move across the landscape it just goes out 7 and stops. I'll see if there something I can do to make lava simply flow farther in the coming weeks.

If I add a new block that can't be harvested i'll be moving into the features I don't want to implement till much later in the development of the mod. Such features would tally the type of block being smelted and then when lava emerges out of a vent there would be chance that block type infused lava will be generated. For example lava with diamond in it. Such that if it were rapidly cooled it would become diamond ore again. **I don't want to implement that right now, so it will be a while before such is a thing because of the code that is involved**.
