### ISSUE TITLE
[1.12.2] LD causes Multiple Issues

### ISSUE THREAD

**Issue by Morpheus1101** [kreezxil/Lava-Dynamics#9]
Apologies for not really having an adequate description for the issue, but basically with the pack im running somewhere between LD v2.4.11 and 4.1.21 of which is a very large area to cover as i neglected my pack and lost interest in MC for a while, basically when you load intot he world, mobs etc load but you cant hit them an they dont basically seem to see you, when using chat messages dont appear, all round for about 5-10min or more the server thread of the game is frozen and you cant do anything.  Once it comes good an you move some distance the issue re-occurs

**Comment by kreezxil** [comment]
First: I need a link to your pack
Second: make sure you are updated to the latest version of the mod
Third: goto https://sparkprofiler.github.io and install the version you
need for your pack server, you can get it from their jenkins build, just
drop it into your plugins/mods folder. Use **/spark start|stop** to
generate data. I suggest letting it run for a few minutes while you
demonstrate the lag effect. After you have stopped it, it'll generate a
link, i need that link.

**Comment by Morpheus1101** [comment]
Although the pack is on curse, the vers im working on is more updated but not pushed to curse as yet as im still working on the pack, however here is a link to an export of the pack: https://ufile.io/gue4i

Spark https://sparkprofiler.github.io/#UCNPi2ISrv

**Comment by kreezxil** [comment]
Ok, I verified that LD is wrecking your pack.

I'm going to change the entire thing to alpha, until I can figure out a good way to not hit the game loop so hard.

I'll explain how the mod works since you're a modder yourself you might have a solution for me.

On a block update the mod checks to see if the block being updated is lava or flowing lava and if it isn't it returns control to the game loop.

If it is the required block, then it checks against the configured values as to where the lava should erupt from and how much of it should erupt.

The problem is that this is a dynamic world gen vs a static world gen mod. 

Meaning you could be roaming along and say find this great spot to build your base but then you decide you need more material and when you come back lava has taken it over.

Suppose to be volcanos.

It's been my intention to fix this year, but World of Dragons is taking most of my time.

Upcoming new features that should help, are:
- static models
- - random blocks can output lava
- - random blocks can be different ores
- magma block shafts that generate from those depths, previously more lava.
- removal of the need to rely on a block update event
- still remain dynamic

**Comment by kreezxil** [comment]
so in the meantime either to make the mod poll less try a value of maxYLevel=3, ie only lava between bedrock and 3 will be considered for eruption and volcanoChance to say 10.
That should reduce it considerably but still have the possibility.

Also recommend deleting the config and letting it regenerate.

**Comment by Morpheus1101** [comment]
Thought id check in and see if there is any added progression with this?

**Comment by kreezxil** [comment]
no progress has been made although I changed the status of every release to
alpha. I have some concepts that should change the behavior of the
volcanoes such that intense lag is no longer an issue. It's probably the
way I should've gone in the beginning but I wanted to pursue a concept
first.

**Comment by kreezxil** [comment]
@Morpheus1101 we have created a beta build that should be most helpful to you. Go and check the mod page again, if you haven't done so join my discord too and join the lava-dynamics channel to help steer the mod forward.

https://minecraft.curseforge.com/projects/lava-dynamics/files/2727235
